# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  System.Debug: true
steps:
- task: Application security testing@2022
  inputs:
    projectName: 'CocoaTestOldVersion'
    enableProxy: false
    enableSastScan: false
    enableDependencyScan: true
    dependencyServerURL: 'sca'
    scaTeam: 'Cxserver' 

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
